name: Deploy Sketchify

on:
  push:
    branches:
      - main   # Run pipeline only when changes are pushed to main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint Code
        run: |
          pip install flake8
          flake8 cartoonify_app.py   # Lint only your app file

      # Optional: Add tests if you create test files
      - name: Run Tests
        run: |
          echo "No tests yet!"   # replace with pytest if you add tests

  # NOTE:
  # Streamlit Cloud auto-deploys when you push to main branch.
  # No deploy step needed in Actions.
  notify:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Notify Deployment
        run: |
          echo "✅ Code built successfully!"
          echo "🚀 Your Sketchify app will be auto-deployed by Streamlit Cloud."
          echo "Check it here: https://share.streamlit.io/<your-username>/Sketchify/main/cartoonify_app.py"

