# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Cartoonify App CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 cartoonify_app.py
          - name: Install dependencies
  run: pip install -The job failed because the requirements.txt file is missing from the repository. The step that installs dependencies runsr path/to/your/requirements.tx

      - name: Verify Streamlit App (dry run)
        run: streamlit run cartoonify_app.py --headless --server.port 8501 &
          sleep 5
          curl -f http://localhost:8501 || exit 1
